### ISSUE TITLE
Create an example with @ExpectJdbcBatching in Spring Boot JUnit 5 project

### ISSUE THREAD

**Issue by jeanbisutti** [quick-perf/quickperf-examples#12]
**Description**

The issue aims to show the usefulness of [@ExpectJdbcBatching](https://github.com/quick-perf/doc/wiki/@ExpectJdbcBatching) in the [Spring Boot JUnit 5 Maven module](https://github.com/quick-perf/quickperf-examples/tree/master/springboot-junit5).

**Implementation ideas**

 In the [Spring Boot JUnit 5 Maven module](https://github.com/quick-perf/quickperf-examples/tree/master/springboot-junit5), create a test where insert, update or delete statements can be processed in batch mode. The `spring.jpa.properties.hibernate.jdbc.batch_size` property  is not given in `application.properties`, so JDBC batching can't be enabled, and the test is going to fail. The test will be successful by adding this property with a positive value (as will QuickPerf suggest).

**Comment by amit1307** [comment]
Hello, is this issue still open? I can give it a try if it's still open.

**Comment by jeanbisutti** [comment]
Hello,

The issue is still open. You can work on it.

Tell me if I can help you.

Kind regards,

Jean

**Comment by amit1307** [comment]
Thank you, will give it a try.

**Comment by jeanbisutti** [comment]
Fixed with 270d1ef9329ebd3f1cf5a90ca3a5617342437ee3
