### ISSUE TITLE
Micronaut: PlayerControllerTest does not analyze SQL statements

### ISSUE THREAD

**Issue by jeanbisutti** [quick-perf/quickperf-examples#3]
**Result**
[PERF] You may think that <1> select request was sent to the database
       But in fact <0>...

**Expected result**
[PERF] You may think that <1> select request was sent to the database
       But in fact <3>...

**Comment by jeanbisutti** [comment]
@loicmathieu It seems to work with the integration test: https://github.com/quick-perf/quickperf/pull/43
Could you please have a look?

**Comment by loicmathieu** [comment]
OK, this is an issue on Quickperf side that I already fixed locally. I'll send a PR on Quickperf today.

**Comment by loicmathieu** [comment]
This will be fixed by https://github.com/quick-perf/quickperf/pull/47

**Comment by jeanbisutti** [comment]
Thanks @loicmathieu

**Comment by loicmathieu** [comment]
@jeanbisutti you close it too early ;)

You need to release a new version of QuickPerf and use this new version on the example parent pom to fix the issue as the example parent pom uses stable QuickPerf version not snapshot.

**Comment by jeanbisutti** [comment]
Fix with 1.0.0-RC6 QuickPerf upgrade.
